name: hil_mobile
version: 1.0.0+1
publish_to: none
description: Hold Item List (HIL) Mobile App
environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  pedantic: 1.11.1
  carousel_slider: 4.1.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/icon.png
    - assets/images/logo.png
    - assets/images/splash.png
    - assets/images/auth_background.png
    - assets/icons/hil_management.png
    - assets/icons/hil_management_active.png
    - assets/icons/task_to_do.png
    - assets/icons/task_to_do_active.png
    - assets/icons/setting.png
    - assets/icons/setting_active.png
    - assets/icons/profile.png
    - assets/icons/profile_active.png
